/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TownRouteImport } from './routes/town'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SoulRouteImport } from './routes/soul'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CommandRouteImport } from './routes/command'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsLibraryRouteImport } from './routes/workflows.library'
import { Route as IntegrationsNewRouteImport } from './routes/integrations.new'
import { Route as IntegrationsIntegrationIdRouteImport } from './routes/integrations.$integrationId'
import { Route as ChannelsNewRouteImport } from './routes/channels.new'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels.$channelId'
import { Route as BotsNewRouteImport } from './routes/bots.new'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'
import { Route as AgentsLibraryRouteImport } from './routes/agents.library'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TownRoute = TownRouteImport.update({
  id: '/town',
  path: '/town',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulRoute = SoulRouteImport.update({
  id: '/soul',
  path: '/soul',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsLibraryRoute = WorkflowsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => WorkflowsRoute,
} as any)
const IntegrationsNewRoute = IntegrationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IntegrationsRoute,
} as any)
const IntegrationsIntegrationIdRoute =
  IntegrationsIntegrationIdRouteImport.update({
    id: '/$integrationId',
    path: '/$integrationId',
    getParentRoute: () => IntegrationsRoute,
  } as any)
const ChannelsNewRoute = ChannelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChannelsRoute,
} as any)
const ChannelsChannelIdRoute = ChannelsChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => ChannelsRoute,
} as any)
const BotsNewRoute = BotsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BotsRoute,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => BotsRoute,
} as any)
const AgentsLibraryRoute = AgentsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bots': typeof BotsRouteWithChildren
  '/brain': typeof BrainRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/command': typeof CommandRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/soul': typeof SoulRoute
  '/tools': typeof ToolsRoute
  '/town': typeof TownRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workspaces': typeof WorkspacesRoute
  '/agents/library': typeof AgentsLibraryRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
  '/integrations/new': typeof IntegrationsNewRoute
  '/workflows/library': typeof WorkflowsLibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bots': typeof BotsRouteWithChildren
  '/brain': typeof BrainRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/command': typeof CommandRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/soul': typeof SoulRoute
  '/tools': typeof ToolsRoute
  '/town': typeof TownRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workspaces': typeof WorkspacesRoute
  '/agents/library': typeof AgentsLibraryRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
  '/integrations/new': typeof IntegrationsNewRoute
  '/workflows/library': typeof WorkflowsLibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/bots': typeof BotsRouteWithChildren
  '/brain': typeof BrainRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/command': typeof CommandRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/knowledge': typeof KnowledgeRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/soul': typeof SoulRoute
  '/tools': typeof ToolsRoute
  '/town': typeof TownRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workspaces': typeof WorkspacesRoute
  '/agents/library': typeof AgentsLibraryRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/new': typeof BotsNewRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/channels/new': typeof ChannelsNewRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
  '/integrations/new': typeof IntegrationsNewRoute
  '/workflows/library': typeof WorkflowsLibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/bots'
    | '/brain'
    | '/channels'
    | '/command'
    | '/integrations'
    | '/jobs'
    | '/knowledge'
    | '/logs'
    | '/memory'
    | '/models'
    | '/settings'
    | '/skills'
    | '/soul'
    | '/tools'
    | '/town'
    | '/workflows'
    | '/workspaces'
    | '/agents/library'
    | '/bots/$botId'
    | '/bots/new'
    | '/channels/$channelId'
    | '/channels/new'
    | '/integrations/$integrationId'
    | '/integrations/new'
    | '/workflows/library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/bots'
    | '/brain'
    | '/channels'
    | '/command'
    | '/integrations'
    | '/jobs'
    | '/knowledge'
    | '/logs'
    | '/memory'
    | '/models'
    | '/settings'
    | '/skills'
    | '/soul'
    | '/tools'
    | '/town'
    | '/workflows'
    | '/workspaces'
    | '/agents/library'
    | '/bots/$botId'
    | '/bots/new'
    | '/channels/$channelId'
    | '/channels/new'
    | '/integrations/$integrationId'
    | '/integrations/new'
    | '/workflows/library'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/bots'
    | '/brain'
    | '/channels'
    | '/command'
    | '/integrations'
    | '/jobs'
    | '/knowledge'
    | '/logs'
    | '/memory'
    | '/models'
    | '/settings'
    | '/skills'
    | '/soul'
    | '/tools'
    | '/town'
    | '/workflows'
    | '/workspaces'
    | '/agents/library'
    | '/bots/$botId'
    | '/bots/new'
    | '/channels/$channelId'
    | '/channels/new'
    | '/integrations/$integrationId'
    | '/integrations/new'
    | '/workflows/library'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  BotsRoute: typeof BotsRouteWithChildren
  BrainRoute: typeof BrainRoute
  ChannelsRoute: typeof ChannelsRouteWithChildren
  CommandRoute: typeof CommandRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  JobsRoute: typeof JobsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SoulRoute: typeof SoulRoute
  ToolsRoute: typeof ToolsRoute
  TownRoute: typeof TownRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/town': {
      id: '/town'
      path: '/town'
      fullPath: '/town'
      preLoaderRoute: typeof TownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul': {
      id: '/soul'
      path: '/soul'
      fullPath: '/soul'
      preLoaderRoute: typeof SoulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/library': {
      id: '/workflows/library'
      path: '/library'
      fullPath: '/workflows/library'
      preLoaderRoute: typeof WorkflowsLibraryRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/integrations/new': {
      id: '/integrations/new'
      path: '/new'
      fullPath: '/integrations/new'
      preLoaderRoute: typeof IntegrationsNewRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/$integrationId': {
      id: '/integrations/$integrationId'
      path: '/$integrationId'
      fullPath: '/integrations/$integrationId'
      preLoaderRoute: typeof IntegrationsIntegrationIdRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/channels/new': {
      id: '/channels/new'
      path: '/new'
      fullPath: '/channels/new'
      preLoaderRoute: typeof ChannelsNewRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/bots/new': {
      id: '/bots/new'
      path: '/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof BotsNewRouteImport
      parentRoute: typeof BotsRoute
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof BotsRoute
    }
    '/agents/library': {
      id: '/agents/library'
      path: '/library'
      fullPath: '/agents/library'
      preLoaderRoute: typeof AgentsLibraryRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsLibraryRoute: typeof AgentsLibraryRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsLibraryRoute: AgentsLibraryRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface BotsRouteChildren {
  BotsBotIdRoute: typeof BotsBotIdRoute
  BotsNewRoute: typeof BotsNewRoute
}

const BotsRouteChildren: BotsRouteChildren = {
  BotsBotIdRoute: BotsBotIdRoute,
  BotsNewRoute: BotsNewRoute,
}

const BotsRouteWithChildren = BotsRoute._addFileChildren(BotsRouteChildren)

interface ChannelsRouteChildren {
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
  ChannelsNewRoute: typeof ChannelsNewRoute
}

const ChannelsRouteChildren: ChannelsRouteChildren = {
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
  ChannelsNewRoute: ChannelsNewRoute,
}

const ChannelsRouteWithChildren = ChannelsRoute._addFileChildren(
  ChannelsRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsIntegrationIdRoute: typeof IntegrationsIntegrationIdRoute
  IntegrationsNewRoute: typeof IntegrationsNewRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIntegrationIdRoute: IntegrationsIntegrationIdRoute,
  IntegrationsNewRoute: IntegrationsNewRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface WorkflowsRouteChildren {
  WorkflowsLibraryRoute: typeof WorkflowsLibraryRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsLibraryRoute: WorkflowsLibraryRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  BotsRoute: BotsRouteWithChildren,
  BrainRoute: BrainRoute,
  ChannelsRoute: ChannelsRouteWithChildren,
  CommandRoute: CommandRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  JobsRoute: JobsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SoulRoute: SoulRoute,
  ToolsRoute: ToolsRoute,
  TownRoute: TownRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  WorkspacesRoute: WorkspacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
